### PR TITLE
Add section on luafile vs lua require()

### PR DESCRIPTION
**Pull request by nanotee**
I added a section following the discussion in #1. Not sure about the wording yet, I hope it's not confusing

### CODE REVIEW

**Comment by clason** [comment]
Nice! Maybe add that you can use `package.loaded[module]=nil` to force lua to re-`require` a module? Or is this too "niche"? Too many details can start being confusing...

**Comment by alerque** [comment]
@clason I think I'd leave that out. True it can be useful in some circumstances, but outside of some debugging edge cases if that move is part of your design you're probably doing something wrong. I wouldn't want to put that in some new Lua coder's back of tricks when what they should be doing is structuring their loaded modules properly so they can be re-instantiated (or whatever is required) in the first place.

**Comment by clason** [comment]
True, and the write-up is specifically about "lua for neovim", which this isn't.

**Comment by nanotee** [comment]
Yeah, I thought it would be confusing for people who are not familiar with Lua so I left that part out. I have some TODOs in "general tips and recommendations" and I was thinking about mentioning this technique for reloading modules automatically as you're working on them

**Pull request merged**
