### PR TITLE
fix(intro): add motivation

### PR DESCRIPTION
**Pull request by matu3ba**
also include benchmarks, curated list of plugins and fix 2 typos

### CODE REVIEW

**Comment by matu3ba** [comment]
Can you think of more plugin examples for raw speed requirements and extensebility, which would have significant worse user experience or maintenance issues in vimscript?

**Comment by nanotee** [comment]
Mhh, there's already [the neovim wiki FAQ](https://github.com/neovim/neovim/wiki/FAQ#why-embed-lua-instead-of-x) and [tjdevries' VimConf presentation](https://www.youtube.com/watch?v=IP3J56sKtn0), can't we just link those? They're from core devs so that's all the more reason to include them

> Can you think of more plugin examples for raw speed requirements and extensebility, which would have significant worse user experience or maintenance issues in vimscript?

I've never really had a problem with Vimscript plugins personally? Language performance is rarely a bottleneck in the plugins I use, so I'm not sure what you have in mind

**Comment by matu3ba** [comment]
@nanotee Ping. Is this okay like this? I updated the neovim FAQ for the performance comparison of luajit and two important wiki articles about luajit performance.

**Comment by nanotee** [comment]
Looks good to me! Thanks for your contributing and updating the wiki as well :+1:!

**Pull request merged**
